### ISSUE TITLE
In Description please which WinVersion

### ISSUE THREAD

**Issue by blackcrack** [stax76/OpenWithPlusPlus#1]
In Description please which WinVersion ..
but i don't know if it's a thing of WinVersion, i have running Win7

![Screen 00000](https://user-images.githubusercontent.com/7925717/54472117-852ca080-47c3-11e9-8c00-7df361759ebf.jpg)

**Comment by stax76** [comment]
Theoretically it should run on Win 7, I remember the exact same error message somebody reported on another app I used to code (staxrip) but I don't remember the reason. The GUI targets .NET 4.7.2 so you can try to install that and maybe it runs then.

If you really want to run it or see this error often also for other apps you can google it and try some of the suggestions.

The GUI is a normal .NET app that don't do anything special so totally common on Windows so there might be a issue with your system.

Unfortunately I can't test it on Win 7, sorry if I can't help much.

**Comment by blackcrack** [comment]
Hi @stax76 
maybe is too new also not really well.. i guess, i have all updated up to the newest 
net version, i fellow the whole Security-updates and security-preview's for Win7, load it down and save it for building a batch-patch.cmd for fresh installed Win7 with 15 Gig .. so should be all updated..
well, maybe have an other a solution, let wait us for an other one, who view this and have a solution for your Proggy  :) :+1: 
best regards
blacky

**Comment by blackcrack** [comment]
resolved with Rlease 1.2 :) :+1:  super :smile:

**Comment by stax76** [comment]
Good to hear, thanks for reporting.

**Comment by blackcrack** [comment]
you service my as user, i service u as The Programmer, 
Both worlds needs together.. and today don't need's razio anymore  ;)
let it clean up together.. :smile: 
it works in //linuxserver/ and in local fs..
something could be also something for Reactos..
... if.. the latest netfx works in ros... finally ...
(if the WinXP step would not be)
