### ISSUE TITLE
Icon in context menu

### ISSUE THREAD

**Issue by Tragen** [stax76/OpenWithPlusPlus#10]
Now we have Icons in the context menu, but no icon for the Open with++ context menu. You should use the yellow plus icon of the exe

**Comment by stax76** [comment]
It will be supported in the upcoming release.

There will be a new icon used and which icon to show can be customized by replacing the icon file.

**Comment by stax76** [comment]
Now available

**Comment by yashpalgoyal1304** [comment]
https://github.com/stax76/OpenWithPlusPlus/commit/2f08de922078f5527534d2ade01db1f30b2613bb
