### ISSUE TITLE
Let Open With++ read and change existing context menu entries?

### ISSUE THREAD

**Issue by pstein** [stax76/OpenWithPlusPlus#14]
As far as I can see Open With++ can only remove context menu entries it creates itself in the past.

Is there really no way to let Open With++ read/retrieve existing context menu entries created by other tools/manually created)
for removal?

What if I want to change only the parameters for an existing context menu?
I cannot do this with Open With++.

Peter

**Comment by stax76** [comment]
This does not fit into Open with++ in my opinion.

I disable existing entries with .reg files, this takes some expertise, so might not applicable for everybody, it also might appear inconvenient, not for programmers, for them, it's a natural thing. I keep those reg files for later reuse.

Shell extensions can be disabled in a way that is easy to reverse:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked]
"{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}"="DropBox"
```

To delete keys, a minus can be put in front:

```
Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\regfile\shell\edit]

[-HKEY_CLASSES_ROOT\regfile\shell\print]
```

Before I do that, I usually make a backup first, which can be done with the key export feature of Regedit.

A long time ago, I made a tool called File Type Registry Viewer, it's still available on download sides:

https://www.softpedia.com/get/Tweak/Registry-Tweak/File-Type-Registry-Viewer.shtml

I still use this tool when dealing with file types, I think it is still useful, I will put it on GitHub.

**Comment by yashpalgoyal1304** [comment]
> I think it is still useful, I will put it on GitHub.

yeah, that will help 😃

**Comment by stax76** [comment]
It's now online:

https://github.com/stax76/File-Type-Registry-Viewer


All my apps:

https://stax76.github.io/frankskare/
