### ISSUE TITLE
Get Filename?

### ISSUE THREAD

**Issue by Neltulz** [stax76/OpenWithPlusPlus#17]
I noticed that %paths% will get the entire path to the selected file

but is there a way to get the filename with or without the extension?

Example:
![image](https://user-images.githubusercontent.com/7741742/105871238-baf55f80-5fbe-11eb-8693-a6d139f28ce8.png)

**Comment by stax76** [comment]
It's not supported, but I can add it when I have time.

**Comment by stax76** [comment]
Added in last release.

https://github.com/stax76/OpenWithPlusPlus#arguments

**Comment by skygate2012** [comment]
@stax76 Can you please also add %ext%
