### ISSUE TITLE
CTRL works for folders but not for files

### ISSUE THREAD

**Issue by crazyyzarc** [stax76/OpenWithPlusPlus#18]
The action is hidden as specified when CTRL is not pressed. However, I can operate any other file without pressing CTRL with the action

![2021-02-08 13_04_42-Open with++ 3 8 0 0](https://user-images.githubusercontent.com/4954535/107217435-7336f500-6a0e-11eb-86db-e255b2d4efe5.png)

![2021-02-08 13_08_52-Open with++](https://user-images.githubusercontent.com/4954535/107217624-b5f8cd00-6a0e-11eb-94a9-98d35891e64f.png)

**Comment by stax76** [comment]
Fixed in last release.
