### ISSUE TITLE
安装时OpenWithPPShellExtension.dll注册失败

### ISSUE THREAD

**Issue by phcole** [stax76/OpenWithPlusPlus#2]
在程序内执行Install报错
![regsvr32](https://user-images.githubusercontent.com/1930736/63160276-f3fe7600-c04f-11e9-8f3d-ffc5751c2d06.png)

在目录中执行regsvr32 OpenWithPPShellExtension.dll报错如下：
![regsvr32](https://user-images.githubusercontent.com/1930736/63159617-856ce880-c04e-11e9-98ce-6e88192feb32.png)

系统：windows 10 build 17763.rs5_release.180914-1434 x64

主程序可以打开并编辑菜单，但是无法安装上。

系统里安装过VC++的运行库包集
![regsvr32](https://user-images.githubusercontent.com/1930736/63160398-3d4ec580-c050-11e9-914e-a8f83dc12475.png)

**Comment by Lichtenshtein** [comment]
Same issue here...

**Comment by stax76** [comment]
I speak only German and English.
