### ISSUE TITLE
OW++ integration with WebMConverter

### ISSUE THREAD

**Issue by fhtdtdj** [stax76/OpenWithPlusPlus#21]
Hi Stax, not sure if that's an issue with OW++ or WebMConverter, but when I assign
https://gitgud.io/nixx/WebMConverter
with video filetypes and the %paths% argument, video don't open with it. 
Any idea how I could get it to work with it? Thanks.

**Comment by stax76** [comment]
Task Manager or Process Explorer allow viewing which command line was used to start a process. I suggest checking the command line that way.

**Comment by fhtdtdj** [comment]
Ended up being unrelated to the Arguments box; Managed to get it working by adding the working dir to program filepath instead of blank/default.
