### ISSUE TITLE
Can not be used with .url type of shortcuts

### ISSUE THREAD

**Issue by maxz-GitHub** [stax76/OpenWithPlusPlus#22]
basically the title.
when for example you take a url from chrome, highlight it and move it to your desktop it will create a shortcut to visit the site.
sadly open with ++ does not work with these kinda data types.
would be really nice to include that

**Comment by stax76** [comment]
It does not make sense to me, maybe try to elaborate.

**Comment by yashpalgoyal1304** [comment]
the following video doesnt end at 1:03 😅, i was just reading that warning (and forgot to keep my mouse moving to show continuity). the video has more part to show, please watch it complete

i hope the following video helps in showing following things and thus making the matter much more clear:
* how is that .url file created
* how does that open


https://user-images.githubusercontent.com/19423063/143470913-5f84d70c-5046-4aab-844e-f033c6039250.mp4

**Comment by stax76** [comment]
I think Windows does not show any shell extension when right-clicking a .url file, there is nothing I could do against that.
