### ISSUE TITLE
Unable to work with multiple shortcuts?

### ISSUE THREAD

**Issue by Chris763454357** [stax76/OpenWithPlusPlus#25]
My goal is to be able to create playlist in mpv.net from shortcuts, dragging them into mpv.net causes mpv.net not to load anything.

I installed this tool hoping "Add to mpv.net playlist" listed in the readme would work. It does not (it only loads the video of the file you right clicked on).

If you use the 'Copy Paths' I found the fundamental problem: Selecting multiple shortcuts only sends the path of the shortcut that you right clicked on (and interestingly it does not even send the path of the shortcut itself, but the actual path that the shortcut resolves to).

**Comment by stax76** [comment]
You've written much, which is good when making a request, unfortunately I don't understand anything.

Please write more clearly.

**Comment by Chris763454357** [comment]
You have a configuration setting in your readme called "Copy Paths". It has a Powershell script that does the following:
Set-Clipboard ($args -join "`r`n")

If you run that script after selecting 2 or more shortcuts in windows it will only give you the path of the first shortcut.

**Comment by stax76** [comment]
You can select normal files like media files (I don't understand what you mean with selecting shortcuts (.lnk files)), with normal files the `Copy Paths` configuration and script absolutely support multiple files and folders selection, I'm very sure about this because it's a very common use case of mine, I just verified that it works.

I've you are not using Win 10 maybe check your PowerShell version:

```
PS D:\Work> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

You might be doing something fundamental wrong, maybe post some screenshots.

**Comment by Chris763454357** [comment]
I am on Windows 10 (LTSC, it has PSVersion 5.1.19041.1682). I could not find any download link for this tool, and had to compile it myself (I used VS 2022 as it was what I had already installed and had to do a 'retarget project'), so I suppose there is a chance that I messed something up.

Here are my results if I run the "Copy Paths" commands in different situations:

- If I select files, folders, or a mixture of the two the "Copy Paths" works as expected.

- If I select shortcuts, it only ever pulls the item I activated the script on (and its real path not the lnk path).

- If I select a mixture of folders, files and shortcuts the tool will display all items if I ran it on a file or folder, but all the shortcuts point to the lnk file and not the file path. And if I do this same test but instead run it on the shortcut, it will only display the real path of that shortcut without displaying any other item.

**Comment by stax76** [comment]
On GitHub, you can find downloads on the release page, search for 'release' on the front page, it's on the right side in the middle.

I don't know if the issue can be fixed, probably difficult, I'm not very experienced in C++, most code was written 15 years ago.

More info:

https://www.google.com/search?q=icontextmenu+shortcut+lnk
