### ISSUE TITLE
Is it possible to edit the title "Open With++" on context menu?

### ISSUE THREAD

**Issue by chip33** [stax76/OpenWithPlusPlus#28]
Is there a way, maybe an edit in the registry to change the title "Open With++"  on the root folder on the context menu?
I would like to be able to rename it to match other custom context menu items I have.
Thanks for a great program.

**Comment by stax76** [comment]
It's not possible and not planned.

**Comment by chip33** [comment]
Ah, that is a shame, I hope you may reconsider this as it would be a great feature. I also get the standard Open with and Open with++ menus confused sometimes when working.
