### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by davidmef** [stax76/OpenWithPlusPlus#5]
Probably it is a very silly thing, but I cannot install it.
This is Windows 8.1.
I unzip OpenWithPP-3.0.0.0.7z in C:\Users\D\Portable\OpenWithPlusPlus.
I click OpenWithPPGUI.exe. 
The window opens.
I click Install.
I confirm.
A warning appears that it will install the DLL.
Then a RegSvr32 window says that it could not load the module c:\Users\D\Portabl...\OpenWithPPShellExtension.dll.
However the DLL file is there. 
What is the problem?

Thanks for your work.

**Comment by stax76** [comment]
Maybe your system isn't 64-bit, I don't provide 32-bit builds.

**Comment by davidmef** [comment]
It is a 64-bit operating system with an x64 processor.

I have tried also the 2.1.0.0 version. It fails in the same way.

I noticed that the Details tab of the DLL has most fields empty. 7Zip doesn't complain about the integrity of the archive, though.

**Comment by stax76** [comment]
Maybe try register it manually with `regsvr32.exe <dll path>`.

**Comment by davidmef** [comment]
I also tried that:
C:\Users\D\Portable\OpenWithPlusPlus>c:\windows\System32\regsvr32.exe c:\Users\d\Portable\OpenWithPlusPlus\OpenWithPPShellExtension.dll

Could it be a missing dependence?
I installed .NET Framework 4.8 before since I didn't have it.

**Comment by stax76** [comment]
Probably, it's compiled with VC++ 2019.

**Comment by davidmef** [comment]
I installed https://aka.ms/vs/16/release/vc_redist.x64.exe from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads and it still fails.

**Comment by davidmef** [comment]
I rebooted to be sure that every installation had finished but it still fails.

**Comment by ilhamepri** [comment]
check if your folder readonly or not

**Comment by Demitrix2k** [comment]
I am running into the exact same issue, net framework is up to date and everything.

**Comment by ericist** [comment]
**Here's a fix:**
Install Visual Studio Community 2019 and select the 'Desktop development with C++' workload.
Seems like this installs a dependency required for OpenWithPP. Had the same error message on W10 1909 with https://aka.ms/vs/16/release/vc_redist.x64.exe installed.

**Comment by stax76** [comment]
@ericist 

Prior to that did you try VC++ redist 2019 ?

https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ericist** [comment]
@stax76 
Yes I did, the redist you linked is the same as the one in my comment.
I'm not too familiar with VC++, if you open the VS installer, deselect everything but C++ desktop dev. and look under individual components you might get an idea of what it's installing besides the redist.

**Comment by whudwl** [comment]
same issue here.

**Comment by BeardedOranges** [comment]
I downloaded 'Desktop development with C++' on my Visual Studio Community 2019 and the error went away for me. I already had .NET Framework 4.8 installed, so that did the trick. Hope this information will help you guys!

**Comment by stax76** [comment]
The problem is I released a debug build instead of a release build.

I hope I have soon time to make a new release.

**Comment by stax76** [comment]
This should now be fixed:

https://github.com/stax76/OpenWithPlusPlus/releases

**Comment by yzhang-gh** [comment]
Have the same issue with v3.6.0.0 😥

**Comment by stax76** [comment]
It's probably not the same problem because the old problem was the release of debug builds.

Dependency Walker shows that v3.6.0.0 uses VCRUNTIME140.DLL, if it was a debug build then it would show VCRUNTIME140**D**.DLL

**Comment by yzhang-gh** [comment]
> Prior to that did you try VC++ redist 2019 ?
> 
> https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads

I tried this and it works now. Thank you!

**Comment by stax76** [comment]
Ok, I've updated the Setup instructions:

https://github.com/stax76/OpenWithPlusPlus#setup
