### ISSUE TITLE
Hide the "Open with++" menu

### ISSUE THREAD

**Issue by tversteeg** [stax76/OpenWithPlusPlus#6]
Would it be possible to hide the "Open with++" menu item?

**Comment by stax76** [comment]
Yes, I consider to support that.

**Comment by yzhang-gh** [comment]
Would love to see this too.

**Comment by stax76** [comment]
I've just released a new version which does support this feature, if the sub menu is empty then it is not shown.

**Comment by yashpalgoyal1304** [comment]
https://github.com/stax76/OpenWithPlusPlus/commit/004ab7e4f286dbced1de0006be2a97c3892ab6c7
