### ISSUE TITLE
Some boxes are missing

### ISSUE THREAD

**Issue by halsek** [stax76/OpenWithPlusPlus#8]
As you can see below, some interface options are missing, like "Show in sub menu", "Show for directories", "Run as admin" and "Run hidden".

![OpenWithPPGUI](https://user-images.githubusercontent.com/62797112/77823053-f2f9f080-70d6-11ea-96b4-7c2daf0f8120.png)

In addition, the program window is also shown a bit small on my screen and there is no way to resize it.
Is there any possible reason for this?

Great tool, by the way. Thanks for that.

**Comment by stax76** [comment]
What OS, resolution and DPI zoom do you have?

**Comment by halsek** [comment]
OS: Windows 10 Pro x64
Resolution: 1366x768 
DPI: 100

It's a laptop.

**Comment by stax76** [comment]
Please try version 3.4.0.0 and close the issue if it works.

https://github.com/stax76/OpenWithPlusPlus/releases

**Comment by halsek** [comment]
Version 3.4.0.0 is working perfectly! Thanks a lot.

Closing.

**Comment by halsek** [comment]
I won't reopen the bug because they're unrelated, but I think it's pertinent to comment that I found a bug in version 3.4.0.0. 

![OpenWithPPGUI](https://user-images.githubusercontent.com/62797112/77852040-d7641800-71b2-11ea-8161-3edbc7001f49.png)

As you can see above, the icon field turns red when you select the desired icon after detection. In this case, after confirmation, no icon is shown in the right-click context menu. But if while the red field is shown, I delete the "0" and put it manually works as it should.

It's not critical, but you might want to take a look at it. Thank you.

**Comment by stax76** [comment]
Please try 3.5.0.0.

**Comment by halsek** [comment]
It's solved. Thanks.
