### ISSUE TITLE
First entry below the sub menu is shown without the icon

### ISSUE THREAD

**Issue by halsek** [stax76/OpenWithPlusPlus#9]
While the sub menu is not displayed:
![fvnRMqlIMM](https://user-images.githubusercontent.com/62797112/77922251-34c19d00-7277-11ea-9d95-1f73dd85966c.png)

While the sub menu is displayed:
![T8b6fkoh4T](https://user-images.githubusercontent.com/62797112/77921776-96353c00-7276-11ea-85ee-2f390121fa1e.png)

The version I'm using is 3.5.0.0.

**Comment by stax76** [comment]
It was not completely easy to reproduce but after some experimenting I was able to reproduce it, investigating now. I hope it's easy to fix and won't cause other issues.

**Comment by stax76** [comment]
Please try 3.6.0.0

https://github.com/stax76/OpenWithPlusPlus/releases

**Comment by halsek** [comment]
Solved. Thanks for your efforts, Stax.
